language: php

php:
  - '5.6'
  - '7.0'
  - 'hhvm'
  - 'nightly'

before_script:
  - composer install --dev --prefer-source --no-interaction
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE `laravel-boilerplate`;'
  - php artisan migrate

script: phpunit

services:
  - mysql

